import { Inter } from "next/font/google";
import "./globals.css";
import AuthWrapper from "./component/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Role based",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}><AuthWrapper>{children}</AuthWrapper></body>
    </html>
  );
}
